### ISSUE TITLE
Isolating LIDAR issues

### ISSUE THREAD

**Issue by GizmoGoody** [jdredd87/NeatoToolio#3]
@jdredd87

Thank you for creating this tool. I'm trying to use it to troubleshoot my D7 as described here:

https://www.robotshop.com/community/for ... es/69743/6

Bottom line is that the LIDAR turret is not spinning, so I think I need to figure out if the LDS board or motor is the problem.

Nothing happens when I click TestLDS and wait a few minutes. Any recommendations for how I should use Toolio to help isolate the faulty LIDAR component(s)?

**Comment by jdredd87** [comment]
Hmm if its connecting and other sensors work then possibly dead Lidar motor or board?

If the lidar is mapping out a big circle... or just a single point.. ( forget which right now ) then its getting no mapping data.

You can use the Debug tab / then raw data tab and should see the commands and responses coming back.

The Lidar will/should return 360 mapping points of data. If no data from lidar, be 0 ( or 0.00 ) coming back for all
360* of data that isn't reporting.

if wanna use Debug/Terminal and try manually

TestMode ON
Setldsrotation ON

Only two commands you should need to turn the Lidar on and start spinning.

The lidar motor I think for most part as far as I know, no real sensory data from that. As its 2 just wires.  Power and ground.
No signal wire or anything out of it. Motor being PWM driven to control the RPM. 5v power I think. 

One problem i've seen is the ribbon cable between the main board and the lidar/wheel motor/blah controller board burning a wire or two ( or more maybe ) as something got it hot.

Have you taken it apart yet?  If not it is super easy.

If commands don't do anything, can try and inspect ribbon cable.

If it looks good, pull the motor wire for the lidar, and give it 5v manually to see if it starts spinning.

I've had around 6 bad lidars this year I've replaced in units.  From bad motors, to bad controller board, to bad
laser optics.  Very touchy and not very stout setup sadly.

**Comment by GizmoGoody** [comment]
Thanks! I had already taken it apart and was so focused on the LIDAR assembly that I hadn’t inspected anywhere else. The ribbon cable is burned through the shielding in two spots and one of the wires is broken. Any recommendations for where to buy the replacement ribbon cable?
![CF0498C0-6F7D-4D8B-B7B4-FE75AC9C37B1](https://user-images.githubusercontent.com/46235745/95150761-d43b7d00-073d-11eb-871f-9906680f1f42.jpeg)

**Comment by GoodyGizmos** [comment]
I saw your post on this thread.

http://www.robotreviews.com/chat/viewtopic.php?f=20&t=22156&start=20

Do you still have any spare ribbon cables?

**Comment by jdredd87** [comment]
I got mine from eBay @ https://www.ebay.com/itm/5-Pcs-FFC-Flexible-Flat-Cable-Ribbon-4-6-8-10-12-20Pin-Pitch-0-5-1-0mm-AWM-20624/223586000134?ssPageName=STRK%3AMEBIDX%3AIT&var=522328913857&_trksid=p2057872.m2749.l2649

**Comment by jdredd87** [comment]
Yah I got a bunch left.
If live in the US, give me an address and can mail you out a few.
-Steven Chesser

	-----------------------------------------From: "GoodyGizmos" 
To: "jdredd87/NeatoToolio"
Cc: "Steven Chesser", "Mention"
Sent: Monday October 5 2020 10:30:53PM
Subject: Re: [jdredd87/NeatoToolio] Isolating LIDAR issues (#3)

	I saw your post on this thread. 

	
[1]http://www.robotreviews.com/chat/viewtopic.php?f=20&t=22156&start=20
[2] 

	Do you still have any spare ribbon cables? 

	—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub [3], or unsubscribe
[4]. 

Links:
------
[1]
http://www.robotreviews.com/chat/viewtopic.php?f=20&t=22156&start=20
[2]
http://www.robotreviews.com/chat/viewtopic.php?f=20&t=22156&start=20
[3]
https://github.com/jdredd87/NeatoToolio/issues/3#issuecomment-703991666
[4]
