### ISSUE TITLE
D7 Usage

### ISSUE THREAD

**Issue by mdblack98** [jdredd87/NeatoToolio#6]
How does one use this with the D7?  There is no USB port under the battery anymore and not clear how to hook up using TCP.

**Comment by Shamshala** [comment]
> How does one use this with the D7? There is no USB port under the battery anymore and not clear how to hook up using TCP.

Your D7 doesn't have microUSB under the dustbin?

**Comment by mdblack98** [comment]
Ahhh...just discovered it...wasn't looking at the front vertical area.Got it hooked up via serial now....
I guess it doesn't have TCP capability?
Mike

 

    On Monday, January 9, 2023 at 11:49:15 AM CST, Shamshala ***@***.***> wrote:  
 
 



How does one use this with the D7? There is no USB port under the battery anymore and not clear how to hook up using TCP.


Your D7 doesn't have microUSB under the dustbin?
